from typing import Protocol

class IntelligenceContract(Protocol):
    def collect(self): ...
    def analyze(self): ...
    def confidence(self) -> float: ...
    def recommendation(self) -> dict: ...
