from abc import ABC, abstractmethod
class BaseIntelligence(ABC):
    @abstractmethod
    def collect(self): ...
    @abstractmethod
    def analyze(self): ...
    @abstractmethod
    def confidence(self): ...
    @abstractmethod
    def recommendation(self): ...
